# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Simple PactEnabled Consumer

on:
  push:
    branches: [ master ]
    paths:
    - 'Simple-PactEnabled-Consumer/*'  
  pull_request:
    branches: [ master ]
    paths:
    - 'Simple-PactEnabled-Consumer/*' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file Simple-PactEnabled-Consumer/pom.xml
    - name: curl
      run: curl -v -XPUT -H 'Content-Type:application/json' --upload-file Simple-PactEnabled-Consumer/target/pacts/simple_consumer-simple_provider.json http://18.194.74.172:9292/pacts/provider/simple_provider/consumer/simple_consumer/version/0.0.0+$GITHUB_SHA
    - name: Trigger provider build
      run: curl  -H "Authorization:token ${TOKEN}" -H 'Accept:application/vnd.github.everest-preview+json' "https://api.github.com/repos/jacekokrojek/simple-pact-projects/dispatches" -d '{"event_type":"awesomeness", "client_payload":{"foo":"bar"}}'
    - name: Get pack-broker cli
      run: wget https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.84.0/pact-1.84.0-linux-x86.tar.gz
    - name: unzip pack-broker cli
      run: tar -zxvf pact-1.84.0-linux-x86.tar.gz  
    - name: can I deploy
      run: chmod a+x pact/bin/pact-broker & pact/bin/pact-broker can-i-deploy --pacticipant=simple_consumer -b http://18.194.74.172:9292/ --latest  